### ISSUE TITLE
Prevent shadow jar from automatically being added as publish artifact

### ISSUE THREAD

**Issue by mgroth0** [GradleUp/shadow#783] opened 2022-07-22 17:35 UTC
I've noticed that if a Project applies the ShadowJar plugin, that shadow jars are automatically added to the maven publication. I do not want this. I read the [docs on maven publishing](https://imperceptiblethoughts.com/shadow/publishing/#publishing-with-maven-publish-plugin) but it was confusing and didn't seem to explain how to disable shadow jars from automatically being added as artifacts in publications.

**Comment by rjrudin** [comment] 2024-04-26 19:53
@mgroth0 Did you find any solution for this? Ran into the same thing today, would like to prevent the shadow jar from being published but cannot find a mechanism for doing so.

**Comment by rjrudin** [comment] 2024-04-26 20:01
Looks like this incantation does the trick - https://github.com/johnrengelman/shadow/issues/586#issuecomment-708375599 . 

This ticket can likely be closed as a duplicate of #586, which is still requesting that the publication of the shadow jar not be enabled by default.

**Closed as not planned** 2024-05-05 06:06 UTC
